### PR TITLE
refactor: clean, improve code quality, remove axios, closes #3

### PR DESCRIPTION
**Pull request by Helias**
I would like to remove the `https://wotlk.murlocvillage.com/` part, I don't think it's necessary, may in another PR if you agree

### CODE REVIEW

**Comment by Miorey** [comment]
@Helias you speak about 
```js
const resp = await fetch(`https://wotlk.murlocvillage.com/api/items/${item}/${displayId}`).then((response) => response.json());
        const res = resp.data ? resp.data : resp;
```
If yes it's not a good idea some stuff displayid have a new display id this endpoint allows to switch. Maybe I will create an independent endpoint so there will be no link with my private server.

**Comment by Helias** [comment]
Ok 👌, thanks for the quick response

**Review by Miorey — APPROVED** [review]
@Helias I approve but I will remove the optional chaining on 
`choiceId: (CHARACTER_PART[prop]) ? part.Choices[character[CHARACTER_PART[prop]]]?.Id : part.Choices[0].Id`
because it can cause trubles on existing project. Thank you for your nice job !

**Comment by Helias** [comment]
@Miorey I added it because if I use demo.html and I change the race to "1" (human), I get error messages, that optional chaining it's to prevent that

**Comment by Miorey** [comment]
@Helias  I like the it because it avoids errors on un-existing attributes child’s but it generates error in vue and webpack seems to not handle it properly. I will add a simple check even if it's dirtier it will let the lib functional in any case.

**Pull request merged**
